import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/scss/index.scss";

import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const notoSans = localFont({
	src: [
		{
			path: "../../public/fonts/NotoSans-VariableFont.ttf",
		},
	],
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={notoSans.className}>
			<body>
				<Header />
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
